name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test [Node, TypeScript]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12.x
          - 14.x
        ts-version:
          - 3.3.x
          - 3.4.x
          - 3.5.x
          - 3.6.x
          - 3.7.x
          - 3.8.x
          - 3.9.x
          - 4.0.x
          - 4.1.x
          - 4.2.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use TypeScript ${{ matrix.ts-version }}
        run: yarn add --dev typescript@${{ matrix.ts-version }}
      - name: Install
        run: yarn install
      - name: Run Lint
        run: yarn lint:ci
      - name: Run Tests
        run: yarn test:ci
